[tool.poetry]
name = "var2rst"
version = "0.1.0"
description = "Replace substitutions in rst files with variables."
authors = ["Jeonghun-Ban <junghoon.ban@gmail.com>"]
license = "MIT"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
